### PR TITLE
upgraded minimum TLS version to 1.2

### PR DESCRIPTION
**Pull request by packeteer**
upgrade TLS version from 1.0 to 1.2

### CODE REVIEW

**Review by iuriaranda — APPROVED** [review]

**Comment by iuriaranda** [comment]
Hi @packeteer, thanks for your contribution.

I've set the PR to be reviewed by the team, once it gets two approvals I'll merge it and create a new release of the module

**Review by minniux — APPROVED** [review]

**Review by simonrondelez — CHANGES_REQUESTED** [review]
it would be better to move the `minimum_protocol_version` and `origin_ssl_protocols` to parameters with a default value. That way other users of this module can still override the options for their use case.  @packeteer are you willing to amend your PR with this change?

**Comment by packeteer** [comment]
yeah, I'll have a go.

closing this PR, and I'll resubmit.

**Comment by packeteer** [comment]
I've reviewed my position on this, TLS1.2 should be the minimum version in use, so I will not be submitting a new PR.
There's a good guide here on which TLS version to use:
https://www.ssl.com/article/guide-to-tls-standards-compliance/

**Comment by iuriaranda** [comment]
While I do agree that supporting TLS versions previous to 1.2 should be avoided, I think it's not the responsibility of this module to make that decision, but it's up to the users to evaluate and decide which level of security they want on their website. Given that AWS allows to set a minimum TLS version up until 1.0, I don't think it would be appropriate to limit that range of choices in this module.

I do believe that it's up to this module to provide a default usage following security best practices. That's why I propose the following:

- Add a variable to set the `minimum_protocol_version` parameter on the Cloudfront viewer certificate configuration. This variable defaults to `TLSv1.2_2018`. This will allow module users to lower their security level if they deem it necessary based on their potential users
- Keep `origin_ssl_protocols` to `["TLSv1.2"]` as that is only used on the internal connection between Cloudfront and S3, and we know that both ends support that TLS version. I think that this is ok to enforce in the module as it doesn't affect the usability of the module nor the website it creates.

What do you think? Would you support such change?

**Comment by packeteer** [comment]
That's a good solution. I'll have a go at implementing

**Pull request closed without merging**
