### PR TITLE
Add profile variable

### PR DESCRIPTION
**Pull request by amanbolat**
#21 add profile variable to work correctly in multiple environments

### CODE REVIEW

**Comment by ringods** [comment]
@amanbolat I think that it will be better if I take the `provider` block out of module. Adding the `provider` attribute will support you, but will break other people's setup.

**Comment by amanbolat** [comment]
@ringods adding `provider` and setting non-default profile  to main.tf didn't solve that problem for me.

**Comment by MattiasGees** [comment]
I am also more in favour of removing the provider block from the module. There are a lot of possible [arguments](https://www.terraform.io/docs/providers/aws/index.html#argument-reference) you can give a provider and I feel those arguments should not become part of the module.

cc @ringods

**Comment by ringods** [comment]
Now that the provider has been removed from the module, this PR will no longer be merged in. Let's keep the discussion in #21

**Pull request closed without merging**
