### PR TITLE
Make "deployer" optional

### PR DESCRIPTION
**Pull request by arjitj2**
Link to issue: https://github.com/skyscrapers/terraform-website-s3-cloudfront-route53/issues/43

### CODE REVIEW

**Review by iuriaranda — COMMENTED** [review]
Could you use `null` as default value instead? That's more suited to signal that a given variable is not set or not used. Other than that, LGTM

**Comment by arjitj2** [comment]
Made the requested changes @iuriaranda, thanks for the feedback!

**Review by iuriaranda — APPROVED** [review]

**Comment by iuriaranda** [comment]
Thanks @arjitj2 ! I'll cut a new release with your changes. It will be version 5.3.0

**Comment by douglaspaulino** [comment]
the following error occurred after this last update :(

```
Error: Missing resource instance key

  on .terraform/modules/dev-app/site-main/main.tf line 84, in resource "aws_iam_policy_attachment" "site-deployer-attach-user-policy":
  84:   policy_arn = aws_iam_policy.site_deployer_policy.arn

Because aws_iam_policy.site_deployer_policy has "count" set, its attributes
must be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    aws_iam_policy.site_deployer_policy[count.index]
```

**Comment by iuriaranda** [comment]
opsie, I have missed that in my review. I've released a new version of the module (5.3.1) with the fix. Sorry about that.

**Pull request merged**
