### PR TITLE
Add possibility to customize not-found-error-path

### PR DESCRIPTION
**Pull request by podviaznikov**
For Single Page Application it's nice to respond with e.x. `index.html` in case of 404.

### CODE REVIEW

**Comment by ringods** [comment]
@podviaznikov could you update the README with this additional variable and add it to the pull request?

**Comment by ringods** [comment]
@podviaznikov reminder...

**Comment by podviaznikov** [comment]
will do @ringods. Didn't see your initial comment

**Comment by podviaznikov** [comment]
@ringods done, please review

**Pull request merged**
